scratch-org-def: config/project-scratch-def.json
assign-permset: true
permset-name: purealoe
run-apex-tests: false
delete-scratch-org: false
show-scratch-org-url: true
data-plans:
  - ./data/Harvest_Field__c-plan.json
  - ./data/Merchandise__c-plan.json
